name: Update "El Pais UY" RSS feed

on:
  push:
    branches:
      - archive

jobs:
  fetch-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch RSS Feed
        uses: Promptly-Technologies-LLC/rss-fetch-action@v2
        with:
          feed_url: 'https://www.elpais.com.uy/rss/'
          file_path: './archive/el-pais-uy.json'

      - name: Commit and push changes to repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update "El Pais UY" RSS feed'
          file_pattern: './archive/el-pais-uy.json'
